"""Add is_hidden to reviews

Revision ID: 15c06608acc4
Revises: d1ab3e932462
Create Date: 2026-07-18 16:58:34.148032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c06608acc4'
down_revision: Union[str, None] = 'd1ab3e932462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_hidden')
    # ### end Alembic commands ###
